import TwitterNavbar from "@/components/twitterNavbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./providers";
import { createUser, dbUser } from "./TestDB";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // console.log("dbUser()", dbUser("alisonborbaa@gmail.com"));
  // console.log("createUser()", createUser("asd@asd.com"));

  return (
    <html lang="en">
      <body className="">
        <NextAuthProvider>
          {/* <TwitterNavbar /> */}
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
